// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vrtlsim_shim.h for the primary calling header

#ifndef VERILATED_VRTLSIM_SHIM_VX_FPU_DPI__N4_O3_H_
#define VERILATED_VRTLSIM_SHIM_VX_FPU_DPI__N4_O3_H_  // guard

#include "verilated.h"


class Vrtlsim_shim__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vrtlsim_shim_VX_fpu_dpi__N4_O3 final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(valid_in,0,0);
        VL_OUT8(ready_in,0,0);
        VL_IN8(mask_in,3,0);
        VL_IN8(tag_in,0,0);
        VL_IN8(op_type,3,0);
        VL_IN8(fmt,1,0);
        VL_IN8(frm,2,0);
        VL_OUT8(has_fflags,0,0);
        VL_OUT8(fflags,4,0);
        VL_OUT8(tag_out,0,0);
        VL_IN8(ready_out,0,0);
        VL_OUT8(valid_out,0,0);
        CData/*3:0*/ __PVT__per_core_valid_out;
        CData/*1:0*/ __PVT__core_select;
        CData/*0:0*/ __PVT__is_fadd;
        CData/*0:0*/ __PVT__is_fsub;
        CData/*0:0*/ __PVT__is_fmul;
        CData/*0:0*/ __PVT__is_fmadd;
        CData/*0:0*/ __PVT__is_fmsub;
        CData/*0:0*/ __PVT__is_fnmadd;
        CData/*0:0*/ __PVT__is_fnmsub;
        CData/*0:0*/ __PVT__is_div;
        CData/*0:0*/ __PVT__is_fcmp;
        CData/*0:0*/ __PVT__is_itof;
        CData/*0:0*/ __PVT__is_utof;
        CData/*0:0*/ __PVT__is_ftoi;
        CData/*0:0*/ __PVT__is_ftou;
        CData/*0:0*/ __PVT__is_f2f;
        CData/*0:0*/ __Vcellinp__div_sqrt_arb__ready_out;
        IData/*19:0*/ __PVT__g_fma__DOT__fflags_fma;
        IData/*19:0*/ __PVT__g_fma__DOT__fflags_fadd;
        IData/*19:0*/ __PVT__g_fma__DOT__fflags_fsub;
        IData/*19:0*/ __PVT__g_fma__DOT__fflags_fmul;
        IData/*19:0*/ __PVT__g_fma__DOT__fflags_fmadd;
        IData/*19:0*/ __PVT__g_fma__DOT__fflags_fmsub;
        IData/*19:0*/ __PVT__g_fma__DOT__fflags_fnmadd;
        IData/*19:0*/ __PVT__g_fma__DOT__fflags_fnmsub;
        CData/*0:0*/ __PVT__g_fma__DOT__fma_valid;
        CData/*0:0*/ __PVT__g_fma__DOT__fma_ready;
        CData/*0:0*/ __PVT__g_fma__DOT__fma_fire;
        CData/*4:0*/ __PVT__g_fma__DOT_____05Ffflags_merged;
        IData/*19:0*/ __PVT__g_fdiv__DOT__fflags_fdiv;
        CData/*0:0*/ __PVT__g_fdiv__DOT__fdiv_valid;
        CData/*0:0*/ __PVT__g_fdiv__DOT__fdiv_ready;
        CData/*0:0*/ __PVT__g_fdiv__DOT__fdiv_fire;
        CData/*4:0*/ __PVT__g_fdiv__DOT_____05Ffflags_merged;
        IData/*19:0*/ __PVT__g_fsqrt__DOT__fflags_fsqrt;
        CData/*0:0*/ __PVT__g_fsqrt__DOT__fsqrt_valid;
        CData/*0:0*/ __PVT__g_fsqrt__DOT__fsqrt_ready;
        CData/*0:0*/ __PVT__g_fsqrt__DOT__fsqrt_fire;
        CData/*4:0*/ __PVT__g_fsqrt__DOT_____05Ffflags_merged;
        IData/*19:0*/ __PVT__g_fcvt__DOT__fflags_fcvt;
        IData/*19:0*/ __PVT__g_fcvt__DOT__fflags_itof;
        IData/*19:0*/ __PVT__g_fcvt__DOT__fflags_utof;
        IData/*19:0*/ __PVT__g_fcvt__DOT__fflags_ftoi;
        IData/*19:0*/ __PVT__g_fcvt__DOT__fflags_ftou;
        CData/*0:0*/ __PVT__g_fcvt__DOT__fcvt_valid;
        CData/*0:0*/ __PVT__g_fcvt__DOT__fcvt_ready;
        CData/*0:0*/ __PVT__g_fcvt__DOT__fcvt_fire;
        CData/*4:0*/ __PVT__g_fcvt__DOT_____05Ffflags_merged;
        IData/*19:0*/ __PVT__g_fncp__DOT__fflags_fncp;
        IData/*19:0*/ __PVT__g_fncp__DOT__fflags_flt;
    };
    struct {
        IData/*19:0*/ __PVT__g_fncp__DOT__fflags_fle;
        IData/*19:0*/ __PVT__g_fncp__DOT__fflags_feq;
        IData/*19:0*/ __PVT__g_fncp__DOT__fflags_fmin;
        IData/*19:0*/ __PVT__g_fncp__DOT__fflags_fmax;
        CData/*0:0*/ __PVT__g_fncp__DOT__fncp_valid;
        CData/*0:0*/ __PVT__g_fncp__DOT__fncp_ready;
        CData/*0:0*/ __PVT__g_fncp__DOT__fncp_fire;
        CData/*4:0*/ __PVT__g_fncp__DOT_____05Ffflags_merged;
        CData/*4:0*/ __Vlvbound_h36ca9328__0;
        CData/*4:0*/ __Vlvbound_h43e316fc__0;
        CData/*4:0*/ __Vlvbound_h26edecc4__0;
        CData/*4:0*/ __Vlvbound_h5d205b05__0;
        CData/*4:0*/ __Vlvbound_h9143e784__0;
        CData/*4:0*/ __Vlvbound_hb471f107__0;
        CData/*4:0*/ __Vlvbound_hd54c3ea3__0;
        CData/*4:0*/ __Vlvbound_h21e41663__0;
        CData/*4:0*/ __Vlvbound_h9f153602__0;
        CData/*4:0*/ __Vlvbound_h301678fe__0;
        CData/*4:0*/ __Vlvbound_h5f715eae__0;
        CData/*4:0*/ __Vlvbound_h2fd415f9__0;
        CData/*4:0*/ __Vlvbound_ha7d3bea0__0;
        CData/*4:0*/ __Vlvbound_hcca9137e__0;
        CData/*4:0*/ __Vlvbound_hed910a88__0;
        CData/*4:0*/ __Vlvbound_h4818f248__0;
        CData/*4:0*/ __Vlvbound_hef2be428__0;
        CData/*4:0*/ __Vlvbound_hb3506ccf__0;
        CData/*4:0*/ __Vlvbound_h54e55b46__0;
        CData/*4:0*/ __Vlvbound_h75b9d2ef__0;
        CData/*4:0*/ __Vlvbound_hd08175d0__0;
        CData/*4:0*/ __Vlvbound_hd08175d0__1;
        CData/*4:0*/ __Vlvbound_hd08175d0__2;
        CData/*4:0*/ __Vlvbound_hd08175d0__3;
        CData/*4:0*/ __Vlvbound_hd08175d0__4;
        CData/*3:0*/ __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__arb_onehot;
        CData/*3:0*/ __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__arbiter__DOT__g_round_robin__DOT__rr_arbiter__DOT__g_model1__DOT__masked_pri_reqs;
        CData/*3:0*/ __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__arbiter__DOT__g_round_robin__DOT__rr_arbiter__DOT__g_model1__DOT__unmasked_pri_reqs;
        CData/*3:0*/ __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__arbiter__DOT__g_round_robin__DOT__rr_arbiter__DOT__g_model1__DOT__reqs_mask;
        CData/*3:0*/ __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__arbiter__DOT__g_round_robin__DOT__rr_arbiter__DOT__g_model1__DOT__masked_reqs;
        CData/*1:0*/ __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__arbiter__DOT__g_round_robin__DOT__rr_arbiter__DOT__g_model1__DOT__onehot_encoder__DOT__g_model1__DOT__g_scan_l__BRA__2__KET____DOT__g_scan_s__BRA__0__KET____DOT__vs;
        CData/*0:0*/ __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__g_out_buf__BRA__0__KET____DOT__out_buf__DOT__g_eb2__DOT__stream_buffer__DOT__g_buffer__DOT__valid_out_r;
        CData/*0:0*/ __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__g_out_buf__BRA__0__KET____DOT__out_buf__DOT__g_eb2__DOT__stream_buffer__DOT__g_buffer__DOT__valid_in_r;
        CData/*0:0*/ __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__g_out_buf__BRA__0__KET____DOT__out_buf__DOT__g_eb2__DOT__stream_buffer__DOT__g_buffer__DOT__flow_out;
        CData/*0:0*/ g_fma__DOT__shift_reg__DOT____Vxrand_h8df6f50b__1;
        CData/*0:0*/ g_fma__DOT__shift_reg__DOT____Vxrand_h8df6f50b__0;
        CData/*0:0*/ g_fma__DOT__shift_reg__DOT____Vlvbound_h30a77c0a__0;
        CData/*0:0*/ g_fma__DOT__shift_reg__DOT____Vlvbound_he07d8e8d__0;
        CData/*0:0*/ g_fma__DOT__shift_reg__DOT____Vlvbound_h42e9b2ab__0;
        CData/*0:0*/ g_fdiv__DOT__shift_reg__DOT____Vxrand_h8df6f50b__1;
        CData/*0:0*/ g_fdiv__DOT__shift_reg__DOT____Vxrand_h8df6f50b__0;
        CData/*0:0*/ g_fdiv__DOT__shift_reg__DOT____Vlvbound_hb89a3195__0;
        CData/*0:0*/ g_fdiv__DOT__shift_reg__DOT____Vlvbound_h7e689713__0;
        CData/*0:0*/ g_fdiv__DOT__shift_reg__DOT____Vlvbound_h48371995__0;
        CData/*0:0*/ g_fsqrt__DOT__shift_reg__DOT____Vxrand_h8df6f50b__1;
        CData/*0:0*/ g_fsqrt__DOT__shift_reg__DOT____Vxrand_h8df6f50b__0;
        CData/*0:0*/ g_fsqrt__DOT__shift_reg__DOT____Vlvbound_h10d88837__0;
        CData/*0:0*/ g_fsqrt__DOT__shift_reg__DOT____Vlvbound_hf0af6e36__0;
        CData/*0:0*/ g_fsqrt__DOT__shift_reg__DOT____Vlvbound_h6b839c03__0;
        CData/*0:0*/ g_fcvt__DOT__shift_reg__DOT____Vxrand_h8df6f50b__1;
        CData/*0:0*/ g_fcvt__DOT__shift_reg__DOT____Vxrand_h8df6f50b__0;
        CData/*0:0*/ g_fcvt__DOT__shift_reg__DOT____Vlvbound_h78b5a936__0;
        CData/*0:0*/ g_fcvt__DOT__shift_reg__DOT____Vlvbound_h895d7db8__0;
        CData/*0:0*/ g_fcvt__DOT__shift_reg__DOT____Vlvbound_h81e316b3__0;
        CData/*0:0*/ g_fncp__DOT__shift_reg__DOT____Vxrand_h8df6f50b__1;
        CData/*0:0*/ g_fncp__DOT__shift_reg__DOT____Vxrand_h8df6f50b__0;
    };
    struct {
        CData/*0:0*/ g_fncp__DOT__shift_reg__DOT____Vlvbound_h432dbf4f__0;
        CData/*0:0*/ g_fncp__DOT__shift_reg__DOT____Vlvbound_h49c93066__0;
        CData/*0:0*/ g_fncp__DOT__shift_reg__DOT____Vlvbound_hf82bc284__0;
        CData/*4:0*/ __Vtask_dpi_fadd__0__fflags;
        CData/*4:0*/ __Vtask_dpi_fsub__1__fflags;
        CData/*4:0*/ __Vtask_dpi_fmul__2__fflags;
        CData/*4:0*/ __Vtask_dpi_fmadd__3__fflags;
        CData/*4:0*/ __Vtask_dpi_fmsub__4__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmadd__5__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmsub__6__fflags;
        CData/*4:0*/ __Vtask_dpi_fdiv__7__fflags;
        CData/*4:0*/ __Vtask_dpi_fsqrt__8__fflags;
        CData/*4:0*/ __Vtask_dpi_itof__9__fflags;
        CData/*4:0*/ __Vtask_dpi_utof__10__fflags;
        CData/*4:0*/ __Vtask_dpi_ftoi__11__fflags;
        CData/*4:0*/ __Vtask_dpi_ftou__12__fflags;
        CData/*4:0*/ __Vtask_dpi_fle__15__fflags;
        CData/*4:0*/ __Vtask_dpi_flt__16__fflags;
        CData/*4:0*/ __Vtask_dpi_feq__17__fflags;
        CData/*4:0*/ __Vtask_dpi_fmin__18__fflags;
        CData/*4:0*/ __Vtask_dpi_fmax__19__fflags;
        CData/*4:0*/ __Vtask_dpi_fadd__23__fflags;
        CData/*4:0*/ __Vtask_dpi_fsub__24__fflags;
        CData/*4:0*/ __Vtask_dpi_fmul__25__fflags;
        CData/*4:0*/ __Vtask_dpi_fmadd__26__fflags;
        CData/*4:0*/ __Vtask_dpi_fmsub__27__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmadd__28__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmsub__29__fflags;
        CData/*4:0*/ __Vtask_dpi_fdiv__30__fflags;
        CData/*4:0*/ __Vtask_dpi_fsqrt__31__fflags;
        CData/*4:0*/ __Vtask_dpi_itof__32__fflags;
        CData/*4:0*/ __Vtask_dpi_utof__33__fflags;
        CData/*4:0*/ __Vtask_dpi_ftoi__34__fflags;
        CData/*4:0*/ __Vtask_dpi_ftou__35__fflags;
        CData/*4:0*/ __Vtask_dpi_fle__38__fflags;
        CData/*4:0*/ __Vtask_dpi_flt__39__fflags;
        CData/*4:0*/ __Vtask_dpi_feq__40__fflags;
        CData/*4:0*/ __Vtask_dpi_fmin__41__fflags;
        CData/*4:0*/ __Vtask_dpi_fmax__42__fflags;
        CData/*4:0*/ __Vtask_dpi_fadd__46__fflags;
        CData/*4:0*/ __Vtask_dpi_fsub__47__fflags;
        CData/*4:0*/ __Vtask_dpi_fmul__48__fflags;
        CData/*4:0*/ __Vtask_dpi_fmadd__49__fflags;
        CData/*4:0*/ __Vtask_dpi_fmsub__50__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmadd__51__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmsub__52__fflags;
        CData/*4:0*/ __Vtask_dpi_fdiv__53__fflags;
        CData/*4:0*/ __Vtask_dpi_fsqrt__54__fflags;
        CData/*4:0*/ __Vtask_dpi_itof__55__fflags;
        CData/*4:0*/ __Vtask_dpi_utof__56__fflags;
        CData/*4:0*/ __Vtask_dpi_ftoi__57__fflags;
        CData/*4:0*/ __Vtask_dpi_ftou__58__fflags;
        CData/*4:0*/ __Vtask_dpi_fle__61__fflags;
        CData/*4:0*/ __Vtask_dpi_flt__62__fflags;
        CData/*4:0*/ __Vtask_dpi_feq__63__fflags;
        CData/*4:0*/ __Vtask_dpi_fmin__64__fflags;
        CData/*4:0*/ __Vtask_dpi_fmax__65__fflags;
        CData/*4:0*/ __Vtask_dpi_fadd__69__fflags;
        CData/*4:0*/ __Vtask_dpi_fsub__70__fflags;
        CData/*4:0*/ __Vtask_dpi_fmul__71__fflags;
        CData/*4:0*/ __Vtask_dpi_fmadd__72__fflags;
        CData/*4:0*/ __Vtask_dpi_fmsub__73__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmadd__74__fflags;
        CData/*4:0*/ __Vtask_dpi_fnmsub__75__fflags;
    };
    struct {
        CData/*4:0*/ __Vtask_dpi_fdiv__76__fflags;
        CData/*4:0*/ __Vtask_dpi_fsqrt__77__fflags;
        CData/*4:0*/ __Vtask_dpi_itof__78__fflags;
        CData/*4:0*/ __Vtask_dpi_utof__79__fflags;
        CData/*4:0*/ __Vtask_dpi_ftoi__80__fflags;
        CData/*4:0*/ __Vtask_dpi_ftou__81__fflags;
        CData/*4:0*/ __Vtask_dpi_fle__84__fflags;
        CData/*4:0*/ __Vtask_dpi_flt__85__fflags;
        CData/*4:0*/ __Vtask_dpi_feq__86__fflags;
        CData/*4:0*/ __Vtask_dpi_fmin__87__fflags;
        CData/*4:0*/ __Vtask_dpi_fmax__88__fflags;
        IData/*19:0*/ __Vxrand_h89e21229__0;
        VlWide<4>/*127:0*/ __Vxrand_hbe6bf8db__0;
        VL_INW(dataa,127,0,4);
        VL_INW(datab,127,0,4);
        VL_INW(datac,127,0,4);
        VL_OUTW(result,127,0,4);
        VlWide<5>/*134:0*/ __Vcellout__div_sqrt_arb__data_out;
        VlWide<4>/*127:0*/ __PVT__g_fma__DOT__result_fma;
        VlWide<4>/*127:0*/ __PVT__g_fdiv__DOT__result_fdiv_r;
        VlWide<4>/*127:0*/ __PVT__g_fsqrt__DOT__result_fsqrt_r;
        VlWide<4>/*127:0*/ __PVT__g_fcvt__DOT__result_fcvt;
        VlWide<4>/*127:0*/ __PVT__g_fncp__DOT__result_fncp;
        VlWide<5>/*134:0*/ div_sqrt_arb__DOT____Vxrand_h8fdbc47e__0;
        VlWide<5>/*134:0*/ rsp_arb__DOT____Vxrand_h8fdbc47e__0;
        VlWide<5>/*136:0*/ rsp_arb__DOT____Vcellinp__g_input_select__DOT__g_arbiter__DOT__g_out_buf__BRA__0__KET____DOT__out_buf__data_in;
        VlWide<5>/*136:0*/ __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__g_out_buf__BRA__0__KET____DOT__out_buf__DOT__g_eb2__DOT__stream_buffer__DOT__g_buffer__DOT__data_out_r;
        VlWide<5>/*136:0*/ __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__g_out_buf__BRA__0__KET____DOT__out_buf__DOT__g_eb2__DOT__stream_buffer__DOT__g_buffer__DOT__buffer_r;
        VlWide<17>/*539:0*/ __PVT__g_fma__DOT__shift_reg__DOT__g_shift_register__DOT__entries;
        VlWide<64>/*2024:0*/ __PVT__g_fdiv__DOT__shift_reg__DOT__g_shift_register__DOT__entries;
        VlWide<43>/*1349:0*/ __PVT__g_fsqrt__DOT__shift_reg__DOT__g_shift_register__DOT__entries;
        VlWide<22>/*674:0*/ __PVT__g_fcvt__DOT__shift_reg__DOT__g_shift_register__DOT__entries;
        VlWide<9>/*271:0*/ __PVT__g_fncp__DOT__shift_reg__DOT__g_shift_register__DOT__entries;
        VlWide<8>/*255:0*/ __PVT__g_fma__DOT__result_fadd;
        VlWide<8>/*255:0*/ __PVT__g_fma__DOT__result_fsub;
        VlWide<8>/*255:0*/ __PVT__g_fma__DOT__result_fmul;
        VlWide<8>/*255:0*/ __PVT__g_fma__DOT__result_fmadd;
        VlWide<8>/*255:0*/ __PVT__g_fma__DOT__result_fmsub;
        VlWide<8>/*255:0*/ __PVT__g_fma__DOT__result_fnmadd;
        VlWide<8>/*255:0*/ __PVT__g_fma__DOT__result_fnmsub;
        VlWide<8>/*255:0*/ __PVT__g_fdiv__DOT__result_fdiv;
        VlWide<8>/*255:0*/ __PVT__g_fsqrt__DOT__result_fsqrt;
        VlWide<8>/*255:0*/ __PVT__g_fcvt__DOT__result_itof;
        VlWide<8>/*255:0*/ __PVT__g_fcvt__DOT__result_utof;
        VlWide<8>/*255:0*/ __PVT__g_fcvt__DOT__result_ftoi;
        VlWide<8>/*255:0*/ __PVT__g_fcvt__DOT__result_ftou;
        VlWide<8>/*255:0*/ __PVT__g_fcvt__DOT__result_f2f;
        VlWide<8>/*255:0*/ __PVT__g_fncp__DOT__result_fclss;
        VlWide<8>/*255:0*/ __PVT__g_fncp__DOT__result_flt;
        VlWide<8>/*255:0*/ __PVT__g_fncp__DOT__result_fle;
        VlWide<8>/*255:0*/ __PVT__g_fncp__DOT__result_feq;
        VlWide<8>/*255:0*/ __PVT__g_fncp__DOT__result_fmin;
        VlWide<8>/*255:0*/ __PVT__g_fncp__DOT__result_fmax;
        VlWide<8>/*255:0*/ __PVT__g_fncp__DOT__result_fsgnj;
        VlWide<8>/*255:0*/ __PVT__g_fncp__DOT__result_fsgnjn;
        VlWide<8>/*255:0*/ __PVT__g_fncp__DOT__result_fsgnjx;
        VlWide<8>/*255:0*/ __PVT__g_fncp__DOT__result_fmvx;
        VlWide<8>/*255:0*/ __PVT__g_fncp__DOT__result_fmvf;
        QData/*63:0*/ __Vtask_dpi_fadd__0__result;
        QData/*63:0*/ __Vtask_dpi_fsub__1__result;
        QData/*63:0*/ __Vtask_dpi_fmul__2__result;
        QData/*63:0*/ __Vtask_dpi_fmadd__3__result;
        QData/*63:0*/ __Vtask_dpi_fmsub__4__result;
        QData/*63:0*/ __Vtask_dpi_fnmadd__5__result;
    };
    struct {
        QData/*63:0*/ __Vtask_dpi_fnmsub__6__result;
        QData/*63:0*/ __Vtask_dpi_fdiv__7__result;
        QData/*63:0*/ __Vtask_dpi_fsqrt__8__result;
        QData/*63:0*/ __Vtask_dpi_itof__9__result;
        QData/*63:0*/ __Vtask_dpi_utof__10__result;
        QData/*63:0*/ __Vtask_dpi_ftoi__11__result;
        QData/*63:0*/ __Vtask_dpi_ftou__12__result;
        QData/*63:0*/ __Vtask_dpi_f2f__13__result;
        QData/*63:0*/ __Vtask_dpi_fclss__14__result;
        QData/*63:0*/ __Vtask_dpi_fle__15__result;
        QData/*63:0*/ __Vtask_dpi_flt__16__result;
        QData/*63:0*/ __Vtask_dpi_feq__17__result;
        QData/*63:0*/ __Vtask_dpi_fmin__18__result;
        QData/*63:0*/ __Vtask_dpi_fmax__19__result;
        QData/*63:0*/ __Vtask_dpi_fsgnj__20__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjn__21__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjx__22__result;
        QData/*63:0*/ __Vtask_dpi_fadd__23__result;
        QData/*63:0*/ __Vtask_dpi_fsub__24__result;
        QData/*63:0*/ __Vtask_dpi_fmul__25__result;
        QData/*63:0*/ __Vtask_dpi_fmadd__26__result;
        QData/*63:0*/ __Vtask_dpi_fmsub__27__result;
        QData/*63:0*/ __Vtask_dpi_fnmadd__28__result;
        QData/*63:0*/ __Vtask_dpi_fnmsub__29__result;
        QData/*63:0*/ __Vtask_dpi_fdiv__30__result;
        QData/*63:0*/ __Vtask_dpi_fsqrt__31__result;
        QData/*63:0*/ __Vtask_dpi_itof__32__result;
        QData/*63:0*/ __Vtask_dpi_utof__33__result;
        QData/*63:0*/ __Vtask_dpi_ftoi__34__result;
        QData/*63:0*/ __Vtask_dpi_ftou__35__result;
        QData/*63:0*/ __Vtask_dpi_f2f__36__result;
        QData/*63:0*/ __Vtask_dpi_fclss__37__result;
        QData/*63:0*/ __Vtask_dpi_fle__38__result;
        QData/*63:0*/ __Vtask_dpi_flt__39__result;
        QData/*63:0*/ __Vtask_dpi_feq__40__result;
        QData/*63:0*/ __Vtask_dpi_fmin__41__result;
        QData/*63:0*/ __Vtask_dpi_fmax__42__result;
        QData/*63:0*/ __Vtask_dpi_fsgnj__43__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjn__44__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjx__45__result;
        QData/*63:0*/ __Vtask_dpi_fadd__46__result;
        QData/*63:0*/ __Vtask_dpi_fsub__47__result;
        QData/*63:0*/ __Vtask_dpi_fmul__48__result;
        QData/*63:0*/ __Vtask_dpi_fmadd__49__result;
        QData/*63:0*/ __Vtask_dpi_fmsub__50__result;
        QData/*63:0*/ __Vtask_dpi_fnmadd__51__result;
        QData/*63:0*/ __Vtask_dpi_fnmsub__52__result;
        QData/*63:0*/ __Vtask_dpi_fdiv__53__result;
        QData/*63:0*/ __Vtask_dpi_fsqrt__54__result;
        QData/*63:0*/ __Vtask_dpi_itof__55__result;
        QData/*63:0*/ __Vtask_dpi_utof__56__result;
        QData/*63:0*/ __Vtask_dpi_ftoi__57__result;
        QData/*63:0*/ __Vtask_dpi_ftou__58__result;
        QData/*63:0*/ __Vtask_dpi_f2f__59__result;
        QData/*63:0*/ __Vtask_dpi_fclss__60__result;
        QData/*63:0*/ __Vtask_dpi_fle__61__result;
        QData/*63:0*/ __Vtask_dpi_flt__62__result;
        QData/*63:0*/ __Vtask_dpi_feq__63__result;
        QData/*63:0*/ __Vtask_dpi_fmin__64__result;
        QData/*63:0*/ __Vtask_dpi_fmax__65__result;
        QData/*63:0*/ __Vtask_dpi_fsgnj__66__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjn__67__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjx__68__result;
        QData/*63:0*/ __Vtask_dpi_fadd__69__result;
    };
    struct {
        QData/*63:0*/ __Vtask_dpi_fsub__70__result;
        QData/*63:0*/ __Vtask_dpi_fmul__71__result;
        QData/*63:0*/ __Vtask_dpi_fmadd__72__result;
        QData/*63:0*/ __Vtask_dpi_fmsub__73__result;
        QData/*63:0*/ __Vtask_dpi_fnmadd__74__result;
        QData/*63:0*/ __Vtask_dpi_fnmsub__75__result;
        QData/*63:0*/ __Vtask_dpi_fdiv__76__result;
        QData/*63:0*/ __Vtask_dpi_fsqrt__77__result;
        QData/*63:0*/ __Vtask_dpi_itof__78__result;
        QData/*63:0*/ __Vtask_dpi_utof__79__result;
        QData/*63:0*/ __Vtask_dpi_ftoi__80__result;
        QData/*63:0*/ __Vtask_dpi_ftou__81__result;
        QData/*63:0*/ __Vtask_dpi_f2f__82__result;
        QData/*63:0*/ __Vtask_dpi_fclss__83__result;
        QData/*63:0*/ __Vtask_dpi_fle__84__result;
        QData/*63:0*/ __Vtask_dpi_flt__85__result;
        QData/*63:0*/ __Vtask_dpi_feq__86__result;
        QData/*63:0*/ __Vtask_dpi_fmin__87__result;
        QData/*63:0*/ __Vtask_dpi_fmax__88__result;
        QData/*63:0*/ __Vtask_dpi_fsgnj__89__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjn__90__result;
        QData/*63:0*/ __Vtask_dpi_fsgnjx__91__result;
        VlUnpacked<VlWide<8>/*255:0*/, 3> __PVT__operands;
        VlUnpacked<CData/*3:0*/, 2> __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__arbiter__DOT__g_round_robin__DOT__rr_arbiter__DOT__g_model1__DOT__onehot_encoder__DOT__g_model1__DOT__addr;
        VlUnpacked<CData/*3:0*/, 3> __PVT__rsp_arb__DOT__g_input_select__DOT__g_arbiter__DOT__arbiter__DOT__g_round_robin__DOT__rr_arbiter__DOT__g_model1__DOT__onehot_encoder__DOT__g_model1__DOT__v;
    };

    // INTERNAL VARIABLES
    Vrtlsim_shim__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vrtlsim_shim_VX_fpu_dpi__N4_O3(Vrtlsim_shim__Syms* symsp, const char* v__name);
    ~Vrtlsim_shim_VX_fpu_dpi__N4_O3();
    VL_UNCOPYABLE(Vrtlsim_shim_VX_fpu_dpi__N4_O3);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
